version: '3.3'
services:
    prometheus:
        container_name: prometheus
        ports:
            - '9090:9090' #modify 9091 to your setup needs
        volumes:
            - './prometheus.yml:/etc/prometheus/prometheus.yml' #modify the path for your install location
        image: prom/prometheus
    grafana:
        container_name: grafana
        ports:
            - '3000:3000' #modify 3457 to your setup needs
        image: grafana/grafana
    node_exporter:
        image: quay.io/prometheus/node-exporter:latest
        container_name: node_exporter
        command:
            - '--path.rootfs=/host'
        pid: host
        restart: unless-stopped
        volumes:
            - '/:/host:ro,rslave'
    cadvisor:
        image: google/cadvisor:latest
        container_name: cadvisor
    # ports:
    #   - "8080:8080"
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:ro
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
            - /dev/disk/:/dev/disk:ro
        devices:
            - /dev/kmsg
        restart: unless-stopped
